const DETAILED_CENSUS_DATA = [
  {
    "Village/Town": " - Total",
    "Total HLBs": 242,
    "In progress": 152,
    "Completed": 0,
    "Yet to start": 90,
    "Total Expected Census Houses": 30436,
    "Total Number of Census Houses": 4783,
    "Wholly Residential": 2926,
    "Partly Residential": 47,
    "Total of Occupied Residential Census Houses": 2973,
    "Vacant Census Houses": 368,
    "Total Locked Census Houses": 36,
    "Total Census Houses (Residential & Vacant)": 3341,
    "Census Houses put to other uses": 1442,
    "Total number of Households": 3027,
    "Households Verified By Supervisor": 159,
    "Total Population": 17274,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 115,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0001 - Amargarh",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 175,
    "Total Number of Census Houses": 137,
    "Wholly Residential": 99,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 99,
    "Vacant Census Houses": 12,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 111,
    "Census Houses put to other uses": 26,
    "Total number of Households": 99,
    "Households Verified By Supervisor": 0,
    "Total Population": 555,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 25,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0002 - Motipura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 99,
    "Total Number of Census Houses": 10,
    "Wholly Residential": 10,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 10,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 10,
    "Census Houses put to other uses": 0,
    "Total number of Households": 10,
    "Households Verified By Supervisor": 0,
    "Total Population": 63,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0003 - Bagrai",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0004 - Kumhariya",
    "Total HLBs": 4,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 215,
    "Total Number of Census Houses": 4,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 1,
    "Census Houses put to other uses": 3,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0005 - Soorajpura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 135,
    "Total Number of Census Houses": 58,
    "Wholly Residential": 45,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 45,
    "Vacant Census Houses": 6,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 51,
    "Census Houses put to other uses": 7,
    "Total number of Households": 45,
    "Households Verified By Supervisor": 0,
    "Total Population": 299,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0006 - Keetap",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 510,
    "Total Number of Census Houses": 48,
    "Wholly Residential": 33,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 33,
    "Vacant Census Houses": 5,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 38,
    "Census Houses put to other uses": 10,
    "Total number of Households": 35,
    "Households Verified By Supervisor": 0,
    "Total Population": 180,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0007 - Sedariya",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 323,
    "Total Number of Census Houses": 16,
    "Wholly Residential": 4,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 4,
    "Vacant Census Houses": 3,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 7,
    "Census Houses put to other uses": 9,
    "Total number of Households": 7,
    "Households Verified By Supervisor": 0,
    "Total Population": 28,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0008 - Chhachhundra",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0009 - Daulatpura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0010 - Pratappura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0011 - Kheri",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 645,
    "Total Number of Census Houses": 74,
    "Wholly Residential": 14,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 14,
    "Vacant Census Houses": 5,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 19,
    "Census Houses put to other uses": 55,
    "Total number of Households": 14,
    "Households Verified By Supervisor": 0,
    "Total Population": 89,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0012 - Padanga",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 733,
    "Total Number of Census Houses": 142,
    "Wholly Residential": 106,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 106,
    "Vacant Census Houses": 7,
    "Total Locked Census Houses": 1,
    "Total Census Houses (Residential & Vacant)": 113,
    "Census Houses put to other uses": 29,
    "Total number of Households": 107,
    "Households Verified By Supervisor": 0,
    "Total Population": 576,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0013 - Bandanwara",
    "Total HLBs": 14,
    "In progress": 11,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 2401,
    "Total Number of Census Houses": 614,
    "Wholly Residential": 275,
    "Partly Residential": 18,
    "Total of Occupied Residential Census Houses": 293,
    "Vacant Census Houses": 62,
    "Total Locked Census Houses": 14,
    "Total Census Houses (Residential & Vacant)": 355,
    "Census Houses put to other uses": 259,
    "Total number of Households": 294,
    "Households Verified By Supervisor": 0,
    "Total Population": 1762,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 2,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0014 - Rooppura",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 110,
    "Total Number of Census Houses": 6,
    "Wholly Residential": 6,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 6,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 6,
    "Census Houses put to other uses": 0,
    "Total number of Households": 6,
    "Households Verified By Supervisor": 0,
    "Total Population": 35,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0015 - Rampura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 71,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0016 - Gajjanadi",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 60,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0017 - Devpura",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 360,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0018 - Arjunpura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 186,
    "Total Number of Census Houses": 41,
    "Wholly Residential": 24,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 24,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 25,
    "Census Houses put to other uses": 16,
    "Total number of Households": 24,
    "Households Verified By Supervisor": 0,
    "Total Population": 123,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0019 - Jheepiya",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 430,
    "Total Number of Census Houses": 23,
    "Wholly Residential": 15,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 15,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 15,
    "Census Houses put to other uses": 8,
    "Total number of Households": 15,
    "Households Verified By Supervisor": 0,
    "Total Population": 82,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0020 - Ratakot",
    "Total HLBs": 4,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 753,
    "Total Number of Census Houses": 254,
    "Wholly Residential": 179,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 179,
    "Vacant Census Houses": 17,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 196,
    "Census Houses put to other uses": 58,
    "Total number of Households": 180,
    "Households Verified By Supervisor": 25,
    "Total Population": 982,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 1,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0021 - Sawaipura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 182,
    "Total Number of Census Houses": 5,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 5,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0022 - Mathaniya",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 196,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0023 - Gowaliya",
    "Total HLBs": 3,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0024 - Karati",
    "Total HLBs": 4,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 374,
    "Total Number of Census Houses": 7,
    "Wholly Residential": 7,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 7,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 7,
    "Census Houses put to other uses": 0,
    "Total number of Households": 8,
    "Households Verified By Supervisor": 0,
    "Total Population": 37,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0025 - Sargaon",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 80,
    "Total Number of Census Houses": 5,
    "Wholly Residential": 1,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 1,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 1,
    "Census Houses put to other uses": 4,
    "Total number of Households": 1,
    "Households Verified By Supervisor": 0,
    "Total Population": 9,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0026 - Gordhanpura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 92,
    "Total Number of Census Houses": 18,
    "Wholly Residential": 10,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 10,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 11,
    "Census Houses put to other uses": 7,
    "Total number of Households": 10,
    "Households Verified By Supervisor": 0,
    "Total Population": 64,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0027 - Jorawarpura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 170,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0028 - Ratanpura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0029 - Bhinay",
    "Total HLBs": 17,
    "In progress": 9,
    "Completed": 0,
    "Yet to start": 8,
    "Total Expected Census Houses": 2318,
    "Total Number of Census Houses": 399,
    "Wholly Residential": 235,
    "Partly Residential": 7,
    "Total of Occupied Residential Census Houses": 242,
    "Vacant Census Houses": 81,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 323,
    "Census Houses put to other uses": 76,
    "Total number of Households": 243,
    "Households Verified By Supervisor": 75,
    "Total Population": 1326,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 20,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0030 - Udaigarh Khera",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 150,
    "Total Number of Census Houses": 23,
    "Wholly Residential": 16,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 16,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 17,
    "Census Houses put to other uses": 6,
    "Total number of Households": 16,
    "Households Verified By Supervisor": 0,
    "Total Population": 98,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0031 - Gujarwara",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0032 - Dhantol",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 227,
    "Total Number of Census Houses": 6,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 6,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0033 - Heerapura",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 120,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0034 - Rammaliya",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 380,
    "Total Number of Census Houses": 83,
    "Wholly Residential": 54,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 54,
    "Vacant Census Houses": 11,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 65,
    "Census Houses put to other uses": 18,
    "Total number of Households": 54,
    "Households Verified By Supervisor": 0,
    "Total Population": 326,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 2,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0035 - Raghunath Garh",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 436,
    "Total Number of Census Houses": 136,
    "Wholly Residential": 97,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 97,
    "Vacant Census Houses": 15,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 112,
    "Census Houses put to other uses": 24,
    "Total number of Households": 99,
    "Households Verified By Supervisor": 0,
    "Total Population": 598,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0036 - Boobkiya",
    "Total HLBs": 3,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0037 - Peeloda",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0038 - Ren",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0039 - Solkhurd",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 150,
    "Total Number of Census Houses": 47,
    "Wholly Residential": 39,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 39,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 41,
    "Census Houses put to other uses": 6,
    "Total number of Households": 39,
    "Households Verified By Supervisor": 0,
    "Total Population": 260,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0040 - Kumhariya Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 84,
    "Total Number of Census Houses": 22,
    "Wholly Residential": 15,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 15,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 2,
    "Total Census Houses (Residential & Vacant)": 15,
    "Census Houses put to other uses": 7,
    "Total number of Households": 15,
    "Households Verified By Supervisor": 0,
    "Total Population": 64,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0041 - Sobri",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 431,
    "Total Number of Census Houses": 1,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 1,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0042 - Pratappura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 140,
    "Total Number of Census Houses": 23,
    "Wholly Residential": 16,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 16,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 1,
    "Total Census Houses (Residential & Vacant)": 17,
    "Census Houses put to other uses": 6,
    "Total number of Households": 16,
    "Households Verified By Supervisor": 0,
    "Total Population": 99,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0043 - Rooppura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 30,
    "Total Number of Census Houses": 21,
    "Wholly Residential": 16,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 16,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 16,
    "Census Houses put to other uses": 5,
    "Total number of Households": 16,
    "Households Verified By Supervisor": 0,
    "Total Population": 94,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0044 - Chawandiya",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 315,
    "Total Number of Census Houses": 41,
    "Wholly Residential": 22,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 22,
    "Vacant Census Houses": 3,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 25,
    "Census Houses put to other uses": 16,
    "Total number of Households": 22,
    "Households Verified By Supervisor": 0,
    "Total Population": 91,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 1,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0045 - Gopalpura",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 155,
    "Total Number of Census Houses": 12,
    "Wholly Residential": 3,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 3,
    "Vacant Census Houses": 3,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 6,
    "Census Houses put to other uses": 6,
    "Total number of Households": 3,
    "Households Verified By Supervisor": 0,
    "Total Population": 12,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0046 - Singhawal",
    "Total HLBs": 5,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 768,
    "Total Number of Census Houses": 93,
    "Wholly Residential": 40,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 40,
    "Vacant Census Houses": 13,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 53,
    "Census Houses put to other uses": 40,
    "Total number of Households": 42,
    "Households Verified By Supervisor": 1,
    "Total Population": 199,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0047 - Khatanon Ka Khera",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0048 - Hiyaliya",
    "Total HLBs": 3,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 334,
    "Total Number of Census Houses": 25,
    "Wholly Residential": 11,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 11,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 11,
    "Census Houses put to other uses": 14,
    "Total number of Households": 11,
    "Households Verified By Supervisor": 0,
    "Total Population": 69,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 1,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0049 - Baneriya",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 248,
    "Total Number of Census Houses": 55,
    "Wholly Residential": 44,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 44,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 5,
    "Total Census Houses (Residential & Vacant)": 44,
    "Census Houses put to other uses": 11,
    "Total number of Households": 44,
    "Households Verified By Supervisor": 0,
    "Total Population": 227,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 11,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0050 - Balapura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 172,
    "Total Number of Census Houses": 30,
    "Wholly Residential": 18,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 18,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 18,
    "Census Houses put to other uses": 12,
    "Total number of Households": 18,
    "Households Verified By Supervisor": 0,
    "Total Population": 105,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0051 - Ekalseenga",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 577,
    "Total Number of Census Houses": 191,
    "Wholly Residential": 146,
    "Partly Residential": 3,
    "Total of Occupied Residential Census Houses": 149,
    "Vacant Census Houses": 14,
    "Total Locked Census Houses": 2,
    "Total Census Houses (Residential & Vacant)": 163,
    "Census Houses put to other uses": 28,
    "Total number of Households": 151,
    "Households Verified By Supervisor": 2,
    "Total Population": 843,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 1,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0052 - Dhani",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0053 - Telara",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 113,
    "Total Number of Census Houses": 51,
    "Wholly Residential": 44,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 44,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 6,
    "Total Census Houses (Residential & Vacant)": 44,
    "Census Houses put to other uses": 7,
    "Total number of Households": 46,
    "Households Verified By Supervisor": 0,
    "Total Population": 240,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 2,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0054 - Ghana",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 435,
    "Total Number of Census Houses": 62,
    "Wholly Residential": 39,
    "Partly Residential": 1,
    "Total of Occupied Residential Census Houses": 40,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 42,
    "Census Houses put to other uses": 20,
    "Total number of Households": 40,
    "Households Verified By Supervisor": 0,
    "Total Population": 274,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0055 - Khayra",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 290,
    "Total Number of Census Houses": 156,
    "Wholly Residential": 124,
    "Partly Residential": 2,
    "Total of Occupied Residential Census Houses": 126,
    "Vacant Census Houses": 12,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 138,
    "Census Houses put to other uses": 18,
    "Total number of Households": 129,
    "Households Verified By Supervisor": 0,
    "Total Population": 821,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 43,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0056 - Peepaliya",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 214,
    "Total Number of Census Houses": 4,
    "Wholly Residential": 2,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 2,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 2,
    "Census Houses put to other uses": 2,
    "Total number of Households": 2,
    "Households Verified By Supervisor": 0,
    "Total Population": 16,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0057 - Sol Kalan",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 145,
    "Total Number of Census Houses": 68,
    "Wholly Residential": 53,
    "Partly Residential": 1,
    "Total of Occupied Residential Census Houses": 54,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 56,
    "Census Houses put to other uses": 12,
    "Total number of Households": 55,
    "Households Verified By Supervisor": 0,
    "Total Population": 325,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0058 - Barla @ Kala Talab",
    "Total HLBs": 3,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 1060,
    "Total Number of Census Houses": 48,
    "Wholly Residential": 35,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 35,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 36,
    "Census Houses put to other uses": 12,
    "Total number of Households": 38,
    "Households Verified By Supervisor": 0,
    "Total Population": 208,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0059 - Keriya Khurd",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 347,
    "Total Number of Census Houses": 4,
    "Wholly Residential": 4,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 4,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 4,
    "Census Houses put to other uses": 0,
    "Total number of Households": 4,
    "Households Verified By Supervisor": 0,
    "Total Population": 25,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0060 - Sapnikhera",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0061 - Bargaon urf Surkhand",
    "Total HLBs": 4,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 661,
    "Total Number of Census Houses": 18,
    "Wholly Residential": 12,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 12,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 12,
    "Census Houses put to other uses": 6,
    "Total number of Households": 12,
    "Households Verified By Supervisor": 2,
    "Total Population": 71,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0062 - Raghunathpura",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 253,
    "Total Number of Census Houses": 101,
    "Wholly Residential": 68,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 68,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 70,
    "Census Houses put to other uses": 31,
    "Total number of Households": 69,
    "Households Verified By Supervisor": 1,
    "Total Population": 425,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0063 - Balapura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0064 - Nagola",
    "Total HLBs": 4,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 970,
    "Total Number of Census Houses": 16,
    "Wholly Residential": 10,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 10,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 10,
    "Census Houses put to other uses": 6,
    "Total number of Households": 10,
    "Households Verified By Supervisor": 0,
    "Total Population": 67,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0065 - Chapaneri",
    "Total HLBs": 8,
    "In progress": 7,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 1397,
    "Total Number of Census Houses": 194,
    "Wholly Residential": 120,
    "Partly Residential": 5,
    "Total of Occupied Residential Census Houses": 125,
    "Vacant Census Houses": 10,
    "Total Locked Census Houses": 5,
    "Total Census Houses (Residential & Vacant)": 135,
    "Census Houses put to other uses": 59,
    "Total number of Households": 133,
    "Households Verified By Supervisor": 4,
    "Total Population": 635,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 3,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0066 - Udaipura Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 158,
    "Total Number of Census Houses": 23,
    "Wholly Residential": 11,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 11,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 11,
    "Census Houses put to other uses": 12,
    "Total number of Households": 11,
    "Households Verified By Supervisor": 0,
    "Total Population": 54,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0067 - Bhairoo Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 125,
    "Total Number of Census Houses": 51,
    "Wholly Residential": 36,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 36,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 37,
    "Census Houses put to other uses": 14,
    "Total number of Households": 36,
    "Households Verified By Supervisor": 0,
    "Total Population": 161,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0068 - Barla Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 120,
    "Total Number of Census Houses": 60,
    "Wholly Residential": 51,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 51,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 51,
    "Census Houses put to other uses": 9,
    "Total number of Households": 51,
    "Households Verified By Supervisor": 11,
    "Total Population": 303,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0069 - Neemera",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 350,
    "Total Number of Census Houses": 76,
    "Wholly Residential": 53,
    "Partly Residential": 1,
    "Total of Occupied Residential Census Houses": 54,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 56,
    "Census Houses put to other uses": 20,
    "Total number of Households": 54,
    "Households Verified By Supervisor": 26,
    "Total Population": 323,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0070 - Jhanbarkiya",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 170,
    "Total Number of Census Houses": 29,
    "Wholly Residential": 21,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 21,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 21,
    "Census Houses put to other uses": 8,
    "Total number of Households": 21,
    "Households Verified By Supervisor": 0,
    "Total Population": 113,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0071 - Barli",
    "Total HLBs": 8,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 4,
    "Total Expected Census Houses": 980,
    "Total Number of Census Houses": 164,
    "Wholly Residential": 99,
    "Partly Residential": 1,
    "Total of Occupied Residential Census Houses": 100,
    "Vacant Census Houses": 10,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 110,
    "Census Houses put to other uses": 54,
    "Total number of Households": 111,
    "Households Verified By Supervisor": 0,
    "Total Population": 748,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0072 - Mataji Ka Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 225,
    "Total Number of Census Houses": 65,
    "Wholly Residential": 30,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 30,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 31,
    "Census Houses put to other uses": 34,
    "Total number of Households": 30,
    "Households Verified By Supervisor": 0,
    "Total Population": 205,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0073 - Ganahera",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 361,
    "Total Number of Census Houses": 49,
    "Wholly Residential": 41,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 41,
    "Vacant Census Houses": 4,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 45,
    "Census Houses put to other uses": 4,
    "Total number of Households": 42,
    "Households Verified By Supervisor": 12,
    "Total Population": 243,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0074 - Lamgara",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 251,
    "Total Number of Census Houses": 10,
    "Wholly Residential": 8,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 8,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 8,
    "Census Houses put to other uses": 2,
    "Total number of Households": 8,
    "Households Verified By Supervisor": 0,
    "Total Population": 51,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0075 - Deoliya Kalan",
    "Total HLBs": 11,
    "In progress": 10,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 1850,
    "Total Number of Census Houses": 405,
    "Wholly Residential": 182,
    "Partly Residential": 5,
    "Total of Occupied Residential Census Houses": 187,
    "Vacant Census Houses": 33,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 220,
    "Census Houses put to other uses": 185,
    "Total number of Households": 193,
    "Households Verified By Supervisor": 0,
    "Total Population": 1138,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 3,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0076 - Moondiya Khera",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 95,
    "Total Number of Census Houses": 3,
    "Wholly Residential": 2,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 2,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 2,
    "Census Houses put to other uses": 1,
    "Total number of Households": 2,
    "Households Verified By Supervisor": 0,
    "Total Population": 13,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0077 - Nandsi",
    "Total HLBs": 3,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 3,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0078 - Padaliya",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 278,
    "Total Number of Census Houses": 58,
    "Wholly Residential": 31,
    "Partly Residential": 1,
    "Total of Occupied Residential Census Houses": 32,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 33,
    "Census Houses put to other uses": 25,
    "Total number of Households": 34,
    "Households Verified By Supervisor": 0,
    "Total Population": 200,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0079 - Gordhanpura",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 130,
    "Total Number of Census Houses": 25,
    "Wholly Residential": 21,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 21,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 21,
    "Census Houses put to other uses": 4,
    "Total number of Households": 21,
    "Households Verified By Supervisor": 0,
    "Total Population": 85,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0080 - Beeliya",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 175,
    "Total Number of Census Houses": 2,
    "Wholly Residential": 2,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 2,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 2,
    "Census Houses put to other uses": 0,
    "Total number of Households": 2,
    "Households Verified By Supervisor": 0,
    "Total Population": 6,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0081 - Kanai Kalan",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 89,
    "Total Number of Census Houses": 27,
    "Wholly Residential": 26,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 26,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 27,
    "Census Houses put to other uses": 0,
    "Total number of Households": 26,
    "Households Verified By Supervisor": 0,
    "Total Population": 114,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0082 - Kanai Khurd",
    "Total HLBs": 2,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 126,
    "Total Number of Census Houses": 51,
    "Wholly Residential": 26,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 26,
    "Vacant Census Houses": 16,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 42,
    "Census Houses put to other uses": 9,
    "Total number of Households": 26,
    "Households Verified By Supervisor": 0,
    "Total Population": 124,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0083 - Dhandhon Ka Khera",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0084 - Nimeda",
    "Total HLBs": 3,
    "In progress": 3,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 391,
    "Total Number of Census Houses": 40,
    "Wholly Residential": 29,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 29,
    "Vacant Census Houses": 2,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 31,
    "Census Houses put to other uses": 9,
    "Total number of Households": 29,
    "Households Verified By Supervisor": 0,
    "Total Population": 175,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0085 - Laxmipura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0086 - Chawandiya",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0087 - Kachariya",
    "Total HLBs": 2,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0088 - Jetpura",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 300,
    "Total Number of Census Houses": 15,
    "Wholly Residential": 12,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 12,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 12,
    "Census Houses put to other uses": 3,
    "Total number of Households": 12,
    "Households Verified By Supervisor": 0,
    "Total Population": 78,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0089 - Kadolai",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 140,
    "Total Number of Census Houses": 5,
    "Wholly Residential": 4,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 4,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 4,
    "Census Houses put to other uses": 1,
    "Total number of Households": 4,
    "Households Verified By Supervisor": 0,
    "Total Population": 24,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0090 - Kerot",
    "Total HLBs": 4,
    "In progress": 4,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 727,
    "Total Number of Census Houses": 149,
    "Wholly Residential": 80,
    "Partly Residential": 2,
    "Total of Occupied Residential Census Houses": 82,
    "Vacant Census Houses": 3,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 85,
    "Census Houses put to other uses": 64,
    "Total number of Households": 82,
    "Households Verified By Supervisor": 0,
    "Total Population": 455,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0091 - Kurthal",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 586,
    "Total Number of Census Houses": 11,
    "Wholly Residential": 3,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 3,
    "Vacant Census Houses": 1,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 4,
    "Census Houses put to other uses": 7,
    "Total number of Households": 3,
    "Households Verified By Supervisor": 0,
    "Total Population": 14,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0092 - Pandonlai",
    "Total HLBs": 1,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 171,
    "Total Number of Census Houses": 25,
    "Wholly Residential": 15,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 15,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 15,
    "Census Houses put to other uses": 10,
    "Total number of Households": 15,
    "Households Verified By Supervisor": 0,
    "Total Population": 72,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0093 - Indrapura",
    "Total HLBs": 1,
    "In progress": 0,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 0,
    "Total Number of Census Houses": 0,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 0,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0094 - Bagrai",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 376,
    "Total Number of Census Houses": 1,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 1,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0095 - Kheri",
    "Total HLBs": 2,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 0,
    "Total Expected Census Houses": 308,
    "Total Number of Census Houses": 23,
    "Wholly Residential": 14,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 14,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 14,
    "Census Houses put to other uses": 9,
    "Total number of Households": 14,
    "Households Verified By Supervisor": 0,
    "Total Population": 84,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0096 - Gurha Khurd",
    "Total HLBs": 3,
    "In progress": 1,
    "Completed": 0,
    "Yet to start": 2,
    "Total Expected Census Houses": 502,
    "Total Number of Census Houses": 2,
    "Wholly Residential": 0,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 0,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 0,
    "Census Houses put to other uses": 2,
    "Total number of Households": 0,
    "Households Verified By Supervisor": 0,
    "Total Population": 0,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  },
  {
    "Village/Town": "0097 - Gurha Kalan",
    "Total HLBs": 3,
    "In progress": 2,
    "Completed": 0,
    "Yet to start": 1,
    "Total Expected Census Houses": 232,
    "Total Number of Census Houses": 22,
    "Wholly Residential": 18,
    "Partly Residential": 0,
    "Total of Occupied Residential Census Houses": 18,
    "Vacant Census Houses": 0,
    "Total Locked Census Houses": 0,
    "Total Census Houses (Residential & Vacant)": 18,
    "Census Houses put to other uses": 4,
    "Total number of Households": 18,
    "Households Verified By Supervisor": 0,
    "Total Population": 89,
    "Total SE ID Generated": 0,
    "Total SE ID Used": 0,
    "Refreshed Date": "20.05.2026",
    "Refreshed Time": "06:18 PM"
  }
];