import re

with open('script.js', 'r', encoding='utf-8') as f:
    c = f.read()

new_render = '''// Generate Detailed Progress Report
function renderReportPanel() {
    const reportPanel = document.getElementById('report-panel');
    if (!reportPanel) return;
    
    // Instead of a custom view, we show the same report generated by admin but embedded in an iframe
    reportPanel.innerHTML = '<iframe id="report-iframe" style="width:100%; height:80vh; border:1px solid #ccc; border-radius:10px;"></iframe>';
    const iframe = document.getElementById('report-iframe');
    
    // Write the report HTML into the iframe
    const html = getReportHTML();
    iframe.contentWindow.document.open();
    iframe.contentWindow.document.write(html);
    iframe.contentWindow.document.close();
}
'''

c = re.sub(r'// Generate Detailed Progress Report \(Top 5 & Bottom 5 Villages\).*?reportPanel\.innerHTML = html;\s*\}', new_render, c, flags=re.DOTALL)

with open('script.js', 'w', encoding='utf-8') as f:
    f.write(c)

print('Updated renderReportPanel successfully.')
